### ISSUE TITLE
Does not work with latest Nuxt 3.1.1 ?

### ISSUE THREAD

**Issue by dosstx** [themesberg/tailwind-nuxt-starter#2]
Cloning the project works fine, but if you run `npx nuxi upgrade --force` to update the version of Nuxt to the latest (3.1.1) then try to run the app, you get a couple of errors:

```js
 ERROR  Cannot start nuxt:  Cannot find module 'C:\Users\XXX\Desktop\work\tailwind-nuxt-starter\node_modules\postcss\node_modules\nanoid\non-secure\index.cjs'
 ```

When looking at the `postcss` dependency, I can see that there is no `non-secure` folder available.

Is it possible we could get the starter to use the latest version of Nuxt 3?

**Comment by dosstx** [comment]
I got it working. I think it was due to my NodeJS version. All good now.

**Comment by KrunalDatascience** [comment]
@dosstx : can you help me understand the issue with the version? how did you solve it. I am unable to see any interactivity even after performing all the required steps.
